### ISSUE TITLE
Try minimal music+SFX test sketch

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#11]
Please try https://github.com/moduscreate/ATMlib/blob/ATMLib2/examples/songs/song01_sfx/song01_sfx.ino... and try to break it! 😉 

The SFX in the example (top of sketch file) has the same structure of a music _score_ for now but it will always start pattern 0 (but we can do better, see https://github.com/moduscreate/ATMlib/issues/8#issuecomment-344539945). All tracker FX and commands are available for SFX. The demo shows how SFX work independently of music; you can pause/unpause,restart a song at any time while a sound effect is playing. The channel occupied by the sound effect is released to the music score when the SFX ends or when it is stopped.

**Comment by jaygarcia** [comment]
@dxxb how did you setup the project to source `<ATMlib.h>` using Header search path ?

**Comment by dxxb** [comment]
I have my ATMlib git repo checkout sym-linked to ~/Documents/Arduino/libraries/ATMlib so any test program finds it.

I received this email but when I click on the link to show GitHub’s issue page this comment doe snot appear >.<!

**Comment by jaygarcia** [comment]
@dxxb Some notes:

- I'm amazed that it uses less RAM and incorporates new features.
- The data structure for the song makes a *ton* more sense than before, and I'm again amazed that it's still only 108bytes!!!


I get errors in isr.c when i comment the following lines out:
``` 
 if (arduboy.justPressed(B_BUTTON)) {
    atm_synth_play_sfx_track(OSC_CH_ONE, (struct mod_sfx*)&sfx1, &sfx_state);
  }

  if (arduboy.justPressed(A_BUTTON)) {
    atm_synth_stop_sfx_track(OSC_CH_ONE);
  }
```

Seems that there is something very wrong w/ having a global reference in the sketch file breaking a core lib file.  What am I not seeing? :)

I can see that you had to make some changes to the `noteTable[]` to compensate for some frequency deltas. I can *hear* that the notes are better aligned to the musical frequency. Fantastic work.
```
const uint16_t noteTable[64] PROGMEM = {
	0,
	274,  291,  308,  326,  346,  366,  388,  411,  435,  461,  489,  518,
	//...
}
```

Getting to test this has made me super excited.

I'll need to rework the JavaScript that produces music now, but that's a small exercise, once I get to understand the new format.

This is friggin awesome.

**Comment by jaygarcia** [comment]
> I received this email but when I click on the link to show GitHub’s issue page this comment doe snot appear >.<!

@dxxb That's because I just threw everything in a single dir and hacked it together to get it to work. :P. I then deleted the comment :P

**Comment by dxxb** [comment]
> I get errors in isr.c when i comment the following lines out:

wow... that the compiler optimising away an array because it thinks it's not used. I fixed it in a4a215ae993582f281f093ac42437d082149de87. I can merge my branch again but beware of 69ea2a8107fce07e028b41f514c8a2f3b7fd393d.

> - I'm amazed that it uses less RAM and incorporates new features.

It has been a fun ride 🤣 I plan to reduce the song structure size for SFX as outlined in https://github.com/moduscreate/ATMlib/issues/8#issuecomment-344539945 and I think I figured out a way to apply any available effects without increasing SRAM usage and at the same time decrease code size. Right now one cannot have a volume slide and a frequency slide at the same time for instance.

> - The data structure for the song makes a *ton* more sense than before, and I'm again amazed that it's still only 108bytes!!!

It haven't changed much. I'm just making the compiler do some work for us.

**Comment by mschwartz** [comment]
I just wanted to chime in.

If you declare a variable in C/C++ and only reference it within an asm block, the compiler will optimize away the array.

I just ran into that on Monday :)

**Comment by dbrignoli** [comment]
@mschwartz, I just fixed it quickly but I did notice it was indeed referenced by a function in use so in theory the compiler should not have optimized it away.

**Comment by dxxb** [comment]
@mschwartz, I just fixed it quickly but I did notice it was indeed referenced by a function in use so in theory the compiler should not have optimized it away.

**Comment by mschwartz** [comment]
If the function you think it’s used by was optimized away, too...

I looked at the code and it is accessed in asm block.

**Comment by dxxb** [comment]
> If the function you think it’s used by was optimized away, too...
> I looked at the code and it is accessed in asm block.

It's also referenced from https://github.com/moduscreate/ATMlib/blob/a4a215ae993582f281f093ac42437d082149de87/src/atm_synth.c#L123 which must always be called on startup. I realise what's happening and why but I am still surprised the compiler feels entitled to make an **extern** symbol go away.

**Comment by dxxb** [comment]
> I can see that you had to make some changes to the noteTable[] to compensate for some frequency deltas. I can hear that the notes are better aligned to the musical frequency. Fantastic work.

Thanks!

> I'll need to rework the JavaScript that produces music now, but that's a small exercise, once I get to understand the new format.
> This is friggin awesome.

Loving it too. But please hold on a little on updating JS tools. I think we can improve code size (and make the code easier to read) if we re-design how commands are encoded. This means making all existing song data invalid...

**Comment by dxxb** [comment]
> I can see that you had to make some changes to the noteTable[] to compensate for some frequency deltas. I can hear that the notes are better aligned to the musical frequency. Fantastic work.

The original array has frequency values in Hz where the library expected a _per sample_ phase increment (at the lowest level the synth equates 2^16 phase steps to 2π rad). See here for a new note->freq https://github.com/moduscreate/ATMlib/blob/dxxb/dev/extras/frequencyToTone.md

Also note that we never emit a note above 4kHz. We can take advantage of this and lower the sample rate to ~8kHz and free up CPU cycles (or double the number of channels MWAHHAH 👹).

**Comment by jaygarcia** [comment]
Closing this issue as I logged a bug against it.
