### ISSUE TITLE
New command encoding supports delays in the range [1,32] ticks is this good enough?

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#14]
See https://github.com/moduscreate/ATMlib/issues/8#issuecomment-344929277

Delay is an immediate command i.e. encoded directly in the command byte. I can use up more bits in the command byte and make the delay range [1,64] or we can implement an extra _long_ delay command with parameters like original ATMlib did. Comments please!

**Comment by jaygarcia** [comment]
@dxxb after reviewing some of the Team ARG songs, I can see how a faster tempo with extra long delays could be useful.

**Comment by dxxb** [comment]
@jaygarcia, thanks for looking into this. I will implement 16bit delays in ATMlib2 too. I will do that tomorrow.

**Comment by dxxb** [comment]
I have implemented and merged support for delays up to 65534 ticks (as in upstream ATMlib).
