### ISSUE TITLE
Audio distortion: sample rate and PWM rate are too close

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#16]
We use CPU_CLK/512 (~31250Hz) as PWM rate and CPU_CLK/1024 (~15625Hz) as sample rate. The two rates are too close and PWM rate should be raised while keeping the sample rate the same or halve it.

**Comment by jaygarcia** [comment]
Glad you experienced this @dxxb. I thought my arduboy was breaking. :(

**Comment by dxxb** [comment]
There are a few things at play here: XTAL is probably not so stable, PWM rate and sample rate too close and frequency response of the piezo. I think I can fix the PWM/sample rate issue but I'm going to put it off until after you integrate the library in the game. It is an internal change so it doesn't affect the API.

**Comment by dxxb** [comment]
Fixed in bbbfffc9a237d0a58123c2c575c3011d06718cd9
