### ISSUE TITLE
Tremolo/Vibrato depth parameter doesn't behave as expected

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#17]
Depth should indicate the maximum amplitude of the effect. ATMlib instead increments/decrements pitch or volume by the depth value every n cycles.

**Comment by dxxb** [comment]
Proposed change for LFO (i.e. Tremolo, Vibrato) parameters. Instead of setting up the _step_ amount every _n_ ticks specify depth as a fraction of full scale amplitude and the duration in ticks.

```
LFO - Low frequency oscillator applied to one of the synth parameters

Parameter count: 1/2/3

P1
    Size   : 1 byte
    Name   : Oscillator parameter to modulate
    Note   : When only this parameter is present the effect is turned off
    Format : b------pp
              ||||||└└-> Oscillator parameter 0:vol, 1:freq, 3:mod
              └└└└└└---> [reserved]

P2
    Size   : 1 byte
    Name   : LFO depth
    Format : bcddddddd
              |└└└└└└└-> Effect depth i.e. a fraction of peak amplitude: ((d+1)/128)*[peak amplitude]
              └--------> 1: continuous effect, 0: one period
    Note   :
             Volume : [param full scale] is half maximum volume
             Freq.  : [param effect limit] is one full tone from the current note
             Mod    : [param effect limit] is 50% duty

P3
    Size   : 1 byte
    Name   : Configuration
    Note   : Defaults to 0 when not present (update every tick)
    Format : b--nnnnnn
              ||└└└└└└-> (n+1)*4 ticks per period i.e. value [0,63] -> period [4,256] ticks
              └└-------> [reserved]
```

**Comment by jaygarcia** [comment]
I'm OK w/ this change. Though, I don't know enough of these effects to test if the change is successful or not. :(

**Comment by dxxb** [comment]
We now have an app for that! 🤣  See https://github.com/moduscreate/ATMlib/blob/ATMLib2/examples/tests/test_sketch/test_sketch.ino

**Comment by dxxb** [comment]
I changed my mind about this one and I am retiring it. The reason is that it implies using fixed point math internally. In case of frequency LFO it's even worse because to implement vibrato properly we would need to logarithmic and not constant increments/decrements.
