### ISSUE TITLE
songs/song01_sfx example is broken

### ISSUE THREAD

**Issue by jaygarcia** [moduscreate/ATMlib#19]
I recently loaded the `song01_sfx` example and the sfx no longer sounds like it should.  It's playing a single tone, rather than following the pattern that is described.

I just pulled from the ATMLib2 branch and discovered this.

```
commander-keen:ATMlib jgarcia$ git pull origin ATMLib2
From github.com:moduscreate/ATMlib
 * branch            ATMLib2    -> FETCH_HEAD
Already up-to-date.
```

**Comment by jaygarcia** [comment]
https://github.com/moduscreate/ATMlib/issues/11

**Comment by dxxb** [comment]
@jaygarcia the SFX in [song01_sfx](https://github.com/moduscreate/ATMlib/blob/fbdd7c9101928087bcd59170f8aa2f6b4d61a840/examples/songs/song01_sfx/song.h#L126) is a single tone. It wasn't at some point but it is now. Feel free to change it to whatever suits the purpose of test SFX.

**Comment by jaygarcia** [comment]
I am an idiot and *totally* misread the SFX notation. 🤦‍♂️
