### ISSUE TITLE
A song must be playing for SFX to work

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#2]
Channels are active only while song playback is in progress. Fix so SFX work regardless of song playback status.

**Comment by jaygarcia** [comment]
Thanks for assigning this. I found this as a limitation to the library.

**Comment by dxxb** [comment]
As of 010d36b9deb5f152c9439ab73aca250330a30f3f the synth routine turns interrupts on/off based on music or sfx callback registration. When there is something to play it will become active and stop when it's done.
