### ISSUE TITLE
Review volume/frequency slide, glissando and noise retriever counter reset

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#4]
Upstream never reset effect counters which makes effect hard to predict. This is not desirable but in an attempt to keep backwards compatibility these commits https://github.com/moduscreate/ATMlib/commit/cd1b0b69462b8a4e5dbdbe074e4cb471bfb6aaf4 https://github.com/moduscreate/ATMlib/commit/dbe7fa3f5013ecccc5b4ae3322e1433fa1a28cf7 https://github.com/moduscreate/ATMlib/commit/022e301aebaa90d3cbe0c391b9b66b7baab87741 reset counters when the effect is turned off. However, most trackers reset effect counters on effect-on so ATMlib should probably do the same. @jaygarcia, what is your take on this?

**Comment by jaygarcia** [comment]
I agree @dxxb.  It could be an oversight, or it could also be by design to keep it light weight? Either way, given that we are looking to introduce SFX capabilities, reseting the counter does make sense.

**Comment by dxxb** [comment]
Ack, so I'll change to reset on effect setup and to apply effects after the first delay has expired (like other trackers do).

**Comment by dxxb** [comment]
Fixed in 48391096b0006a0cd1e70938e94b5471a507ca2c
