### ISSUE TITLE
Compiler warnings reported on ARG git repo

### ISSUE THREAD

**Issue by jaygarcia** [moduscreate/ATMlib#7]
@dxxb  please review https://github.com/TEAMarg/ATMlib/issues/12 .

I imagine you've seen these before, but wanted to ensure this is on your radar. =)

**Comment by dxxb** [comment]
I just found out I had not starred the original repo for some reason so I didn't see the bug report. So much has been rewritten that those warnings are not applicable anymore, but others have been introduced (and will be squashed)

**Comment by jaygarcia** [comment]
Thanks =). I'll close this issue.
