### ISSUE TITLE
Backward incompatible changes to song format and commands

### ISSUE THREAD

**Issue by dxxb** [moduscreate/ATMlib#8]
Getting the ball rolling on this one. Breaking backwards compatibility is an unpleasant thing to do but it has the potential to simplify code and thus make it smaller and easier to understand/maintain.

Off of the top of my head I can think of two things that could be improved:
1. Song header layout and track address base can be changed to make it easier to be decoded.
2. The _repeated-call_ command is an extension of _call_ but the parameter's order is different so the code to parse them cannot be factored into a single case.

Comments @jaygarcia?

**Comment by jaygarcia** [comment]
If it helps optimize runtime & data size, yes, let's go for it.

**Comment by dxxb** [comment]
## Score persistent format improvement ideas

| offset | size | label      | description                                            |
|--------|------|------------|--------------------------------------------------------|
| 0      | 1    | version    | Major revision. Changes to indicate incompatible format |
| 1      | 1    | num_chans  | Number of channels                                     |
| 2      | 1    | num_tracks | Number of tracks. |
| 3      | 2\*num\_tracks  | tracks\_offset\_array | Offset of track data from the beginning of score data |
| 3+2*num_tracks | 1\*num_chans  | start\_track\_array | Start track index for each channel |
| 3+2\*num\_tracks+1*num\_chans | first\_track\_offset-[this offset] | available for extensions | |
| first\_track\_offset | second\_track\_offset-first\_track\_offset | track_data | |
| ... | ... | ... | ... |

1. A version byte (maybe reserve the upper two bits for flags) is useful to mark version incompatibilities. It's a must for anything persistent but ATMlib is so minimalistic/special I'm not sure we need it.
2. The number of channels in the score should be specified in the score's data. Right now the player code has it hardcoded but it's bad practice to do so because in case of a mismatch the song will not play (and the MCU most likely crash).
3. num_chan and num_tracks could be stored in the same byte as cctttttt (cc+1 channels) and (tttttt+1 tracks)
4. The track offset table should store offsets from the beginning of the score (offset 0) instead of storing the offset from 1+num_tracks*2+4 like now. Current format means either (1) a 16bit*8bit multiplication and additions or (2) an extra pointer (or offset) has to be stored for each channel. Existing implementation stores an offset per channel. Proposed change would do away with this extra offset (minus 10 bytes in total counting the SFX track)

I care mostly about points 2 and 4 in the list above.

## Command and FX encoding comments

- Track loop command should be per-track (one parameter) instead of per score (four parameters)
- Add tempo command parameter should be signed
- _Repeated-call_ argument list should be in the same order as _call_
- Do we need both slide and slide advanced commands?
- Is it ok to use 64 possible commands to encode the _short_ delay command? Could we use up less command space?

Comments please?

**Comment by jaygarcia** [comment]
1) Versions matter, but this also means that we'll need to have the tools in lock step w/ this library. Not opposed to this, but if we always say "use the latest", we should not need this flag.

2) I agree with this, but assuming the song data isn't bad, we shouldn't run into this issue often, no?  I believe the current model has the flexibility to say "Let me use Channel 1, 2 and 3".  And the format for the "empty" channel simply have a  single value `0x9F`. Strangely enough (see below, please) the base song has "number of tracks" listed as the first byte.  It actually means "number of patterns".  The terms "channel" and "tracks" in this library confuses the shit out of me because they are used interchangeably in the music industry. 

Question: Does the number of tracks (patterns) matter from the song data perspective?   

This is an empty song:
```
#ifndef SONG_H
#define SONG_H

#define Song const uint8_t PROGMEM

Song music[] = {
  0x04,			// Number of tracks
  0x00, 0x00,		// Address of track 0
  0x03, 0x00,		// Address of track 1
  0x04, 0x00,		// Address of track 2
  0x05, 0x00,		// Address of track 3
  0x00,			// Channel 0 entry track
  0x01,			// Channel 1 entry track
  0x02,			// Channel 2 entry track
  0x03,			// Channel 3 entry track
  //"Track channel 0"
  0x9D, 24,		// FX: SET TEMPO: tempo = 24
  0x9F,			// FX: STOP CURRENT CHANNEL
  //"Track channel 1"
  0x9F,			// FX: STOP CURRENT CHANNEL
  //"Track channel 2"
  0x9F,			// FX: STOP CURRENT CHANNEL
  //"Track channel 3"
  0x9F,			// FX: STOP CURRENT CHANNEL
};
#endif
```

3) We could see some space savings by using the same byte, but if we always know that there will be 4 channels (available), no need to state the number of channels, no?

4) If this keeps the current flexibility, yes. Let's do it.


* Track loop command should be per-track (one parameter) instead of per score (four parameters)
Add tempo command parameter should be signed
-- Modern trackers allow you to loop from the pattern data within any channel, however, I don't think there is a need for this lib to do that.  Per-score should be good enough. 

* Repeated-call argument list should be in the same order as call
-- I'm not educated enough on this specific ask. :(

* Do we need both slide and slide advanced commands?
-- I have not used either.  I've not heard the difference between the two and can even say if the differences would be audible on the device.  I'd say leave it in for now. I imagine we could (easily?) rip it out if it's not awesome, no?


* Is it ok to use 64 possible commands to encode the short delay command? Could we use up less command space? 
-- Have no idea why anyone would want to delay notes more than 64 ticks. To save space, the slowest tempo and 1/8th notes are the best thing. If the tempo were doubled and we went to 1/16th notes resolution, data could double.  Even then, a long delay may not entirely be required.

**Comment by dxxb** [comment]
> It actually means "number of patterns". The terms "channel" and "tracks" in this library confuses the shit out of me.

Something else we should change at some point. I am confused too, but I can cope right now because I am wearing ATMlib goggles. Let's try to standardise, we need terms for the following things (please add more as necessary):

- The chunk of memory with the binary representation of the song/score. I'd say 'score' because it's more narrow than song.
- The simulated oscillators computing the waveform. I used to call these 'voices' from the 8-bit personal computer times. in the source code right now 'osc' is used.
- ATMlib has 'channels' which represent the state and active FX being applied to a voice. ATMlib had 1:1 relationship between 'voices' and 'channels' but because we are working on introducing an SFX channel this is not true. It is also no longer true if you consider that we now have 3 identical programable square wave generators so in theory (not planned for implementation at this stage) during the playback of a non-busy music score, one or more SFX could be produced without affecting music playback because the SFX would setup a 'channel' and use it to update any of the free 'voices'. How do we call these?
- Smallest addressable sequence of commands which can be associated to a 'voice'. Patterns (instead of ATMlib _tracks_).

> Question: Does the number of tracks (patterns) matter from the song data perspective?

No, the empty song above could simply have 1 pattern and point all 'channels'/'voices' (argh we really need to establish a glossary!) to it.

1. Agreed regarding not adding the version number.
2. In my comment I meant that the code expects 4 oscillators and the number is hardcoded. The song data MUST always have 4 bytes in the start_track array so a version of the library compiled to have less voices (to save CPU or memory) would crash instead of ignoring the extra bytes (and this is hard to debug).
3. If it's always 4 then no need, but I think people will want to recompile with different channel counts.
4. you left point 4 empty 🤣 

> If you make the AddTempo param signed, does that mean that the entire data set has to go to signed values?

No, you just type a signed integer and the compiler will cast it to unsigned (signed to unsigned cast is loss-less in C, but this doesn't hold for the opposite unsigned to signed).

> Modern trackers allow you to loop from the pattern data within any channel, however, I don't think there is a need for this lib to do that. Per-score should be good enough.

Sorry, I am not sure if you agree with my proposed change or not. The confusing bit is ```Per-score```.

> Do we need both slide and slide advanced commands? I have not used either. I've not heard the difference between the two and can even say if the differences would be audible on the device. I'd say leave it in for now. I imagine we could (easily?) rip it out if it's not awesome, no?

Yes we can rip them out later but I think keeping the advanced one at least would be useful.

> Is it ok to use 64 possible commands to encode the short delay command? Could we use up less command space? Have no idea why anyone would want to delay notes more than 64 ticks.

Ack. So we now have ```delay``` (1-65 ticks, takes up precious bits in the command byte) and ```long delay``` (65-0xFFFF-1 ticks, takes up just one command byte and one or two parameter bytes). I see the advantage in having _delay_ working like _note_ i.e. the command also carries the parameter but I'm trying to figure out if instead of using up the equivalent of 64 commands we could make it use 32 or 48. I just don't know what a good value would be...

:phew: that was a long answer

**Comment by dxxb** [comment]
I am now thinking that the version byte will be very useful for having the same code playback music or SFX of different complexity. For instance:

For music we could use version 0 (full featured tracker):
``` C
uint8_t score[] = {
0, // normal score version
/* patterns offsets */
/* start pattern for each voice */
/* patterns */
};
```

For simple SFX could use version 1 (single pattern):
``` C
uint8_t score[] = {
1, // single pattern sfx version
/* 1 pattern */
};
```

For compact SFX could use version 2 (multiple patterns, max size 256 bytes):
``` C
uint8_t score[] = {
2, // compact pattern sfx version
/* patterns offsets (one byte each) */
/* patterns */
};
```

For large SFX could use version 3 (multiple patterns):
``` C
uint8_t score[] = {
3, // compact pattern sfx version
/* patterns offsets (two byte each like music) */
/* patterns */
};
```

**Comment by dxxb** [comment]
### V2

```-``` means reserved bits. They should be ignored and written as zero.

#### Common header

| Offset | Size | Format    | Label               | Description                                                      |
|--------|------|-----------|---------------------|------------------------------------------------------------------|
| 0      | 1    | ```b------oc``` | Format ID/Version   | Format ID or major revision. o: has pattern offsets, c: uses multiple channels                           |

#### Fully featured music score format (multiple channels, multiple patterns, large offsets)

| Offset | Size | Format    | Label               | Description                                                      |
|--------|------|-----------|---------------------|------------------------------------------------------------------|
| 0      | 1    | ```b------11``` | fmt_id              | Format ID or major revision                                      |
| 1      | 1    | ```b------nn``` | num_chans (C)       | Number of patterns played back simultaneously                    |
| 2      | 1    | ```b----nnnn``` | num_patterns (P)    | Number of patterns                                               |
| 3      | 2\*P | uint16_t[]| patterns\_ofs       | Array of offsets from fmt_id to the start of all patterns        |
| 3+2\*P | 1\*C | uint8_t[] | start_patterns      | First pattern index for each channel                             |
| 3+2\*P+1*C | patterns\_ofs[0]-(3+2\*P+1*C) | N/A    | N/A | available for extensions                               |
| patterns\_ofs[0] | patterns\_ofs[1]-patterns\_ofs[0] | uint8_t[] | pattern0 | pattern 0 data |
| patterns\_ofs[1] | patterns\_ofs[2]-patterns\_ofs[1] | uint8_t[] | pattern1 | pattern 1 data |
| ... | ... | ... | ... |

#### Fully featured SFX (single channel, multiple patterns, large offsets)

| Offset | Size | Format    | Label               | Description                                                      |
|--------|------|-----------|---------------------|------------------------------------------------------------------|
| 0      | 1    | ```b------10``` | fmt_id              | Format ID or major revision                                      |
| 1      | 1    | ```b----nnnn``` | num_patterns (P)    | Number of patterns                                               |
| 2      | 2\*P | uint16_t[]| patterns\_ofs       | Array of offsets from fmt_id to the start of all patterns        |
| 2+2\*P | patterns\_ofs[0]-(2+2\*P) | N/A    | patterns\_ofs[0]-(3+2\*P+C) | available for extensions                               |
| patterns\_ofs[0] | patterns\_ofs[1]-patterns\_ofs[0] | uint8_t[] | pattern0 | pattern 0 data |
| patterns\_ofs[1] | patterns\_ofs[2]-patterns\_ofs[1] | uint8_t[] | pattern1 | pattern 1 data |
| ... | ... | ... | ... |

#### Simple SFX (single channel, single pattern, no offsets)

| Offset | Size | Format    | Label               | Description                                                      |
|--------|------|-----------|---------------------|------------------------------------------------------------------|
| 0      | 1    | ```b------00``` | fmt_id              | Format ID or major revision                                      |
| 1 | N/A | uint8_t[] | pattern0 | Pattern 0 data |

#### Compact Score/SFX

We could use an extra bit (bit2) of the format byte to select between 8 bit and 16 bit pattern offsets. This would enforce a maximum start offset for all patterns of 255 from score/SFX data start.

**Comment by jaygarcia** [comment]
Makes me think we need a web tool to help generate & demonstrate these SFX options =)

**Comment by dxxb** [comment]
#### New command byte encoding

Command bit-space is partitioned to make the parser more compact.

```
00nnnnnn : 1-63 note ON number, 0 note OFF (Immediate)
010ddddd : Delay d+1 ticks (max 32 ticks) (Immediate)
0110iiii : Immediate command ID space (16 commands) (Immediate)
0111---- : [reserved]
1ssscccc : s+1 = parameters byte count (s=7 reserved), c = command ID (16 commands)
1111---- : [reserved]
```

#### Immediate commands

```
00 - Glissando/portamento OFF
01 - Arpeggio OFF
02 - Note Cut OFF
03 - Noise re-trigger OFF
04 - [reserved]
05 - [reserved]
06 - Return
07 - Stop (end pattern marker, stop playback on this channel)
08 - Transpose OFF
[09, 15] - [reserved]
```

Immediate command 1-6 have the same least significant bits as their corresponding parametrised commands below to make the implementation more compact.

#### Parametrised commands

```
00 - Glissando/portamento
01 - Arpeggio
02 - Note Cut
03 - Noise re-trigger
04 - Slide FX
05 - LFO FX
06 - Call
07 - [reserved]
08 - Set transposition
09 - Add transposition
10 - Set tempo
11 - Add tempo
12 - Set Volume
13 - Set square duty cycle
14 - Setup loop
15 - [reserved]
```

**Comment by dxxb** [comment]
#### With current command parser
```
Sketch uses 9406 bytes (32%) of program storage space. Maximum is 28672 bytes.
Global variables use 1425 bytes (55%) of dynamic memory, leaving 1135 bytes for local variables. Maximum is 2560 bytes.
```

#### With new command parser for the commands laid out as detailed above
```
Sketch uses 9042 bytes (31%) of program storage space. Maximum is 28672 bytes.
Global variables use 1425 bytes (55%) of dynamic memory, leaving 1135 bytes for local variables. Maximum is 2560 bytes.
```

-364 progmem bytes with the same features. Code reads a lot better and it's probably faster too.

**Comment by dxxb** [comment]
New command format implemented in 66bb4482cef191fef0d3da9a3b3ed06cf409ca97. @jaygarcia I think you will like the new commands constants and macros. See example usage here https://github.com/moduscreate/ATMlib/blob/66bb4482cef191fef0d3da9a3b3ed06cf409ca97/examples/songs/song01_sfx/song.h#L41

Next I will update the score format as outlined above.

**Comment by jaygarcia** [comment]
That makes the music *so much* easier to read!!

**Comment by dxxb** [comment]
### V3 - Implemented

```-``` means reserved bits. They should be ignored and written as zero.

#### Common header

1 byte at offset 0, always present.

```
0b------oc | Format ID/Version | o: pattern count and offsets array present, c: channel count and entry pattern array present
```

#### Pattern offsets information

This block is present if flag ```o``` is set in the common header. 

```
0b--pppppp | pattern count   | p: number of patterns
uint16_t[p]| pattern offsets | array of p elements, each element P is the offset in bytes of the start of pattern P from the beginning of the score data (including the common header).
```

#### Channel information

This block is present if flag ```c``` is set in the common header. 

```
0b------pp | channel count   | c: number of channels
uint8_t[c] | pattern offsets | array of c elements, each element uint8_t[c_i] is the index of the first pattern played by channel c_i.
```

#### Reserved for extensions

If the ```c``` flag is set in the header, extensions can be located immediately after pattern info (or immediately after channel info in case it is present) and take up space up to the beginning of pattern data. When there are no extensions (non is defined for now) pattern data can immediately follow the previous block.

#### Pattern data

When the ```c``` flag is set in the header each pattern's start offset is specified in the pattern offset information block. When the ```c``` flag is not set pattern data follows immediately the end of the channel information block if present, otherwise it follows the common header.

```
0b------oc | Pattern data offset
        00 | Immediately after the header: 1 byte
        01 | Immediately after channel information block: 2+[number of channels] bytes
        10 | Specified by offset array
        11 | Specified by offset array
```

**Comment by dxxb** [comment]
New file and command format documentation [here](https://github.com/moduscreate/ATMlib/blob/dxxb/dev/README.md), please review.

**Comment by jaygarcia** [comment]
@dxxb, fantastic work on the documentation!!!

**Comment by dxxb** [comment]
Done.
